---
# tasks file for apache
# Role: apache
# File tasks/main.yml
- name: install Apache
  become: true
  yum:
    name: "httpd"
    state: present
  tags:
    - httpd

- name: install Apache SSL Module
  become: true
  yum:
    name: "mod_ssl*"
    state: present
  tags:
    - httpd

- name: be sure HTTPD is running and enabled
  become: true
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
    - httpd
