---
# Role: zabbix-agent
# File tasks/main.yml

- name: be sure libselinux-python are installed
  become: true
  yum:
    name: "libselinux-python"
    state: present
  tags:
    - zabbix
    - zabbix-agent

- name: install the Zabbix agent
  become: true
  yum:
    name: "zabbix-agent"
    state: present
  tags:
    - zabbix
    - zabbix-agent

- name: place custom userparameter files
  become: true
  copy: src={{ item }} dest=/etc/zabbix/zabbix_agentd.d/ owner=root mode=0755
  with_fileglob:
    - zabbix_userparameters/*
  notify:
    - restart zabbix-agent
  tags:
    - zabbix
    - zabbix-agent

- name: be sure zabbix agent scripts directory is present
  become: true
  file: path=/etc/zabbix/scripts state=directory owner=zabbix
      group=zabbix mode=0755
  tags:
    - zabbix
    - zabbix-agent

- name: place the custom zabbix agent scripts
  become: true
  copy: src={{ item }} dest=/etc/zabbix/scripts/ owner=root mode=0755
  with_fileglob:
    - zabbix_scripts/*
  tags:
    - zabbix
    - zabbix-agent

- name: configure the Zabbix agent
  become: true
  template: src="zabbix_agentd.conf.j2" dest=/etc/zabbix/zabbix_agentd.conf
    owner="root" group="root" mode=0644
  notify:
    - restart zabbix-agent
  tags:
    - zabbix
    - zabbix-agent

- name: be sure zabbix-agent is running and enabled
  become: true
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  tags:
    - zabbix
    - zabbix-agent
