---
# Role: zabbix-repo
# File: tasks/main.yml

- name: check if zabbix-repo is installed
  command: rpm -q zabbix-release
  register: zbx_installed
  changed_when: 0
  failed_when: zbx_installed.rc > 1
  tags:
    - zabbix
    - repo

- name: install the Zabbix repository package
  yum:
    name: "{{ zabbix_repo_url }}"
    state: present
  when: zbx_installed.rc == 1
  tags:
    - zabbix
    - repo

- name: import the Zabbix GPG key
  rpm_key:
    key: "{{ zabbix_repo_gpg_key_url }}"
    state: present
  tags:
    - zabbix
    - repo
