---
# tasks file for firewall
- name: make sure firewalld is installed
  yum:
    name: "firewalld"
    state: present
  tags:
    - firewall

- name: Add TCP Ports to firewalld
  firewalld: port={{ item }}/tcp permanent=true state=enabled
  with_items:
    - 80
    - 443
    - 10050
  tags:
    - firewall

- name: Add UDP Ports to firewalld
  firewalld: port={{ item }}/udp permanent=true state=enabled
  with_items:
    - 10051
  notify:
    - restart firewalld
  tags:
    - firewall
