---
# role: zabbix-web
# file: tasks/main.yml
- name: be sure httpd is installed
  become: true
  yum:
    name: "httpd"
    state: present
  tags:
    - zabbix
    - zabbix-web

- name: be sure zabbix-web-mysql is installed
  become: true
  yum:
    name: "zabbix-web-mysql"
    state: present
  tags:
    - zabbix
    - zabbix-web

- name: be sure zabbix-web-mysql is configured
  become: true
  template: src="zabbix.conf.php.j2" dest=/etc/zabbix/web/zabbix.conf.php
    owner="apache" group="apache" mode=0640
  notify:
    - restart httpd
  tags:
    - zabbix
    - zabbix-web

- name: be sure php parameters are correct
  become: true
  copy: src=php.ini dest=/etc/php.ini owner=root group=root mode=0644
  tags:
    - zabbix
    - zabbix-web

- name: be sure httpd is running and enabled
  become: true
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
    - zabbix
    - zabbix-web

- name: Change policy and state of SELinux
  become: true
  selinux:
    state=disabled
