---
# tasks file for common
- name: be sure YUM is configured
  become: true
  copy: src="yum.conf" dest="/etc/yum.conf"
    owner="root" group="root" mode=0644
  tags:
    - repo
    - yum

- name: be sure the server packages are up to date
  become: true
  yum: name=* state=latest

- name: be sure libselinux-python are installed
  become: true
  yum:
    name: "libselinux-python"
    state: present
  tags:
    - selinux

- name: be sure the EPEL repository is enabled
  become: true
  yum:
    name: epel-release
    state: installed
  tags: repo

- name: be sure ntp is installed
  become: true
  yum:
    name: ntp
    state: installed
  tags: ntp

- name: be sure ntp is configured
  become: true
  template: src=ntp.conf.j2 dest="/etc/ntp.conf"
    owner="root" group="root" mode=0644
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  become: true
  service: name=ntpd state=started enabled=yes
  tags:
    - ntp
